#!/bin/bash

# ─────────────────────────────────────────────
#  proxy.sh — system-wide proxy configurator
# ─────────────────────────────────────────────

ENV_FILE="/etc/environment"
PROFILE_FILE="/etc/profile.d/proxy.sh"
APT_CONF="/etc/apt/apt.conf.d/95proxy"

# ── helpers ──────────────────────────────────
red()   { echo -e "\e[31m$*\e[0m"; }
green() { echo -e "\e[32m$*\e[0m"; }
cyan()  { echo -e "\e[36m$*\e[0m"; }
bold()  { echo -e "\e[1m$*\e[0m"; }

check_root() {
  if [[ $EUID -ne 0 ]]; then
    red "Запустите скрипт с правами root: sudo ./proxy.sh"
    exit 1
  fi
}

# ── parse user:pass@host:port ────────────────
parse_proxy() {
  local raw="$1"
  # user:pass@host:port
  if [[ "$raw" =~ ^([^:]+):([^@]+)@([^:]+):([0-9]+)$ ]]; then
    USER="${BASH_REMATCH[1]}"
    PASS="${BASH_REMATCH[2]}"
    HOST="${BASH_REMATCH[3]}"
    PORT="${BASH_REMATCH[4]}"
    return 0
  fi
  # host:port (no auth)
  if [[ "$raw" =~ ^([^:@]+):([0-9]+)$ ]]; then
    USER=""
    PASS=""
    HOST="${BASH_REMATCH[1]}"
    PORT="${BASH_REMATCH[2]}"
    return 0
  fi
  return 1
}

build_url() {
  local scheme="$1"
  if [[ -n "$USER" ]]; then
    echo "${scheme}://${USER}:${PASS}@${HOST}:${PORT}"
  else
    echo "${scheme}://${HOST}:${PORT}"
  fi
}

# ── remove old proxy entries ─────────────────
clean_env_file() {
  sed -i '/^http_proxy=/Id' "$ENV_FILE"
  sed -i '/^https_proxy=/Id' "$ENV_FILE"
  sed -i '/^HTTP_PROXY=/Id' "$ENV_FILE"
  sed -i '/^HTTPS_PROXY=/Id' "$ENV_FILE"
  sed -i '/^socks5_proxy=/Id' "$ENV_FILE"
  sed -i '/^SOCKS5_PROXY=/Id' "$ENV_FILE"
  sed -i '/^all_proxy=/Id' "$ENV_FILE"
  sed -i '/^ALL_PROXY=/Id' "$ENV_FILE"
  sed -i '/^no_proxy=/Id' "$ENV_FILE"
  sed -i '/^NO_PROXY=/Id' "$ENV_FILE"
}

# ── write /etc/environment ───────────────────
write_env() {
  local http_url="$1"
  local socks_url="$2"

  clean_env_file

  {
    echo "http_proxy=\"${http_url}\""
    echo "HTTP_PROXY=\"${http_url}\""
    echo "https_proxy=\"${http_url}\""
    echo "HTTPS_PROXY=\"${http_url}\""
    [[ -n "$socks_url" ]] && echo "all_proxy=\"${socks_url}\""
    [[ -n "$socks_url" ]] && echo "ALL_PROXY=\"${socks_url}\""
    echo "no_proxy=\"localhost,127.0.0.1,::1\""
    echo "NO_PROXY=\"localhost,127.0.0.1,::1\""
  } >> "$ENV_FILE"
}

# ── write /etc/profile.d/proxy.sh ────────────
write_profile() {
  local http_url="$1"
  local socks_url="$2"

  cat > "$PROFILE_FILE" <<EOF
# Generated by proxy.sh — $(date)
export http_proxy="${http_url}"
export HTTP_PROXY="${http_url}"
export https_proxy="${http_url}"
export HTTPS_PROXY="${http_url}"
EOF
  [[ -n "$socks_url" ]] && cat >> "$PROFILE_FILE" <<EOF
export all_proxy="${socks_url}"
export ALL_PROXY="${socks_url}"
EOF
  cat >> "$PROFILE_FILE" <<EOF
export no_proxy="localhost,127.0.0.1,::1"
export NO_PROXY="localhost,127.0.0.1,::1"
EOF
  chmod 644 "$PROFILE_FILE"
}

# ── write apt proxy ───────────────────────────
write_apt() {
  local http_url="$1"
  cat > "$APT_CONF" <<EOF
Acquire::http::Proxy "${http_url}";
Acquire::https::Proxy "${http_url}";
EOF
}

# ── write gsettings (GNOME) ───────────────────
write_gnome() {
  local host="$1" port="$2" user="$3" pass="$4"
  if command -v gsettings &>/dev/null && [[ -n "$DISPLAY" || -n "$WAYLAND_DISPLAY" ]]; then
    gsettings set org.gnome.system.proxy mode 'manual' 2>/dev/null
    gsettings set org.gnome.system.proxy.http  host "$host" 2>/dev/null
    gsettings set org.gnome.system.proxy.http  port "$port" 2>/dev/null
    gsettings set org.gnome.system.proxy.https host "$host" 2>/dev/null
    gsettings set org.gnome.system.proxy.https port "$port" 2>/dev/null
    [[ -n "$user" ]] && gsettings set org.gnome.system.proxy.http  authentication-user "$user" 2>/dev/null
    [[ -n "$pass" ]] && gsettings set org.gnome.system.proxy.http  authentication-password "$pass" 2>/dev/null
    gsettings set org.gnome.system.proxy ignore-hosts "['localhost','127.0.0.1','::1']" 2>/dev/null
    green "  ✔ GNOME proxy настроен"
  fi
}

# ══════════════════════════════════════════════
#  MAIN
# ══════════════════════════════════════════════
check_root

bold "╔══════════════════════════════════════╗"
bold "║      SYSTEM-WIDE PROXY SETUP         ║"
bold "╚══════════════════════════════════════╝"
echo ""

# ── HTTP/HTTPS proxy ─────────────────────────
cyan "Введите HTTP/HTTPS прокси"
cyan "Формат: user:pass@host:port  или  host:port  (или Enter — пропустить)"
echo -n "  http/s proxy > "
read -r INPUT_HTTP

HTTP_URL=""
HTTP_HOST="" HTTP_PORT="" HTTP_USER="" HTTP_PASS=""

if [[ -n "$INPUT_HTTP" ]]; then
  if parse_proxy "$INPUT_HTTP"; then
    HTTP_URL=$(build_url "http")
    HTTP_HOST="$HOST"; HTTP_PORT="$PORT"
    HTTP_USER="$USER"; HTTP_PASS="$PASS"
    green "  ✔ HTTP proxy: $HTTP_URL"
  else
    red "  ✗ Неверный формат, пропускаю HTTP proxy"
  fi
fi

echo ""

# ── SOCKS5 proxy ─────────────────────────────
cyan "Введите SOCKS5 прокси"
cyan "Формат: user:pass@host:port  или  host:port  (или Enter — пропустить)"
echo -n "  socks5 proxy > "
read -r INPUT_SOCKS

SOCKS_URL=""

if [[ -n "$INPUT_SOCKS" ]]; then
  if parse_proxy "$INPUT_SOCKS"; then
    SOCKS_URL=$(build_url "socks5")
    green "  ✔ SOCKS5 proxy: $SOCKS_URL"
  else
    red "  ✗ Неверный формат, пропускаю SOCKS5 proxy"
  fi
fi

echo ""

# ── nothing entered ──────────────────────────
if [[ -z "$HTTP_URL" && -z "$SOCKS_URL" ]]; then
  red "Ничего не введено. Выход."
  exit 1
fi

# ── use socks as fallback for http if needed ──
EFFECTIVE_HTTP="${HTTP_URL:-$SOCKS_URL}"
EFFECTIVE_SOCKS="$SOCKS_URL"

# ── apply ────────────────────────────────────
cyan "Применяю настройки..."

write_env     "$EFFECTIVE_HTTP" "$EFFECTIVE_SOCKS"
write_profile "$EFFECTIVE_HTTP" "$EFFECTIVE_SOCKS"

[[ -n "$HTTP_URL" ]] && write_apt "$HTTP_URL"

[[ -n "$HTTP_HOST" ]] && write_gnome "$HTTP_HOST" "$HTTP_PORT" "$HTTP_USER" "$HTTP_PASS"

# ── apply to current shell ────────────────────
export http_proxy="$EFFECTIVE_HTTP"
export HTTP_PROXY="$EFFECTIVE_HTTP"
export https_proxy="$EFFECTIVE_HTTP"
export HTTPS_PROXY="$EFFECTIVE_HTTP"
[[ -n "$EFFECTIVE_SOCKS" ]] && export all_proxy="$EFFECTIVE_SOCKS"
[[ -n "$EFFECTIVE_SOCKS" ]] && export ALL_PROXY="$EFFECTIVE_SOCKS"

echo ""
bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
green "✅ Готово! Прокси настроен на уровне системы."
bold "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "  /etc/environment      ← переменные окружения"
echo "  /etc/profile.d/proxy.sh ← для новых сессий"
[[ -n "$HTTP_URL" ]] && echo "  /etc/apt/apt.conf.d/95proxy ← apt"
echo ""
cyan "⚠  Чтобы изменения вступили в силу для текущего терминала:"
echo "   source /etc/profile.d/proxy.sh"
echo ""
cyan "⚠  Для GUI-приложений может потребоваться перезаход в сессию."
